# -*- coding: utf-8 -*-
"""nlp task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e8wLSRhCgE9lfhvb-GmXkLrKbKxiwFrR
"""

# installing pypdf2
! pip install pypdf2

# import necessary libraries
import PyPDF2
import random

# tunction to read pdf
def reading_pdf(pdf):
  with open(pdf,'rb') as file:
    reader = PyPDF2.PdfReader(file)
    content = ''
    for i in reader.pages:
      content +=i.extract_text()
    return content

# reading chapter2 pdf
chapter_2 = reading_pdf('/content/drive/MyDrive/chapter-2.pdf')
chapter_2

# reading chapter3 pdf
chapter_3 = reading_pdf('/content/drive/MyDrive/chapter-3.pdf')
chapter_3

# reading chapter4 pdf
chapter_4 = reading_pdf('/content/drive/MyDrive/chapter-4.pdf')
chapter_4

# removing extra spaces at begining and ending
a = chapter_2.strip()
a

#split the data
b = a.split('. ')
b[:10]

# function to generate question and answers
def get_mca_questions(context):
    a = context.strip()
    b = a.split('. ')

    mca_questions = []
    for j in b:
        question = 'Which of the following is true about ' + j + '?'
        choices = random.sample(b, k=2)
        choices.append(j)
        choices.append(j)
        random.shuffle(choices)

        mca_question = question + '\n'
        for i, choice in enumerate(choices):
            mca_question += chr(ord('a') + i) + ') ' + choice + '\n'

        mca_questions.append(mca_question)

    return mca_questions

# generating question and answer for chapter_2, chapter_3, chapter_4 pdfs

chapter = [chapter_2,chapter_3,chapter_4]
for i in chapter:
  questions = get_mca_questions(i)
  for j, question in enumerate(questions):
    print(f'{j+1}: {question}')
  print('\n')
  print('\n')